# argocd-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-notes-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/omkar-shelke25/GitOps-Django-Note-App-GitHub-Action.git
    targetRevision: main
    path: base 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true