apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-app-manager
  namespace: argocd
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-app-access-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: django-note-app-deployer
    namespace: django-note-app
roleRef:
  kind: Role
  name: argocd-app-manager
  apiGroup: rbac.authorization.k8s.io
