apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: django-note-app-rb
  namespace: django-note-app
subjects:
  - kind: ServiceAccount
    name: django-note-app-deployer
    namespace: django-note-app
roleRef:
  kind: Role
  name: django-note-app-role
  apiGroup: rbac.authorization.k8s.io