apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - nginx-service.yaml
  - nginx-deployment.yaml
  - django-service.yaml
  - django-deployment.yaml
  - db-service.yaml
  - db-deployment.yaml
images:
  - name: omkara25/noteapp-nginx
    newName: omkara25/noteapp-nginx
    newTag: "1d2c2f1"
  - name: omkara25/noteapp-backend
    newName: omkara25/noteapp-backend
    newTag: "1d2c2f1"
