# django-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: omkara25/noteapp-backend:86fa11a
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: notes-app-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: notes-app-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notes-app-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              value: db-service  # Refers to MySQL Service
            - name: DB_PORT
              value: "3306"
          resources:
            limits:
              cpu: "500m"    # 0.5 cores
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /admin
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
