# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - nginx-service.yaml
  - nginx-deployment.yaml
  - django-service.yaml
  - django-deployment.yaml
  - db-service.yaml
  - db-deployment.yaml