apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Targets Nginx pods
  ports:
    - protocol: TCP
      port: 80      # External port
      targetPort: 80  # Pod port
      nodePort: 30012
  type: NodePort  # Creates a cloud load balancer (e.g., AWS ELB)
  # Alternative: Uncomment below for NodePort instead of LoadBalancer
  # type: NodePort
  # ports:
  #   - protocol: TCP
  #     port: 80
  #     targetPort: 80
  #     nodePort: 30080  # Accessible on node IP at port 30080
