# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: notes-app-secrets
type: Opaque
data:
  DB_NAME: dGVzdF9kYg==      # base64 encoded "test_db"
  DB_USER: cm9vdA==          # base64 encoded "root"
  DB_PASSWORD: cm9vdA==      # base64 encoded "root"