name: noteapp-gitops-pipelines

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  docker-build-and-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Save Docker Images
        run: |
          docker build -t noteapp-nginx:latest ./nginx
          docker save noteapp-nginx:latest -o noteapp-frontend.tar

          docker build -t noteapp-backend:latest .
          docker save noteapp-backend:latest -o noteapp-backend.tar

      - name: Upload All Docker Images as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            noteapp-nginx.tar
            noteapp-backend.tar
        
