name: noteapp-gitops-pipelines

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - 'feature/**'  # Matches any branch starting with feature/
  pull_request:
    branches:
      - main
    types:
      - closed  # For merge request events

jobs:
  docker-build:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Run Docker Build Commands
        run: echo "docker build"
  
  docker-test:
    runs-on: ubuntu:latest
    steps:
      - name: Docker Image Testing
        uses: actions/checkout@v3
      - run: echo "run Executed without Name"